Repository humanmade/hm-content-import, pull requests merged in 2019-03, with the labels that each got.

#58 57 - Improve meta lookup handling
  inc/classes/class-master.php
  inc/classes/inserter/class-base.php
  inc/classes/inserter/wp/class-attachment.php
  inc/classes/inserter/wp/class-base-interface.php
  inc/classes/inserter/wp/class-base.php
  inc/classes/inserter/wp/class-comment.php
  inc/classes/inserter/wp/class-guest-author.php
  inc/classes/inserter/wp/class-post.php
  inc/classes/inserter/wp/class-term.php
  inc/classes/inserter/wp/class-user.php
  plugin.php
Labels: Breaking Change, enhancement

#53 Fix an incorrect count for the Files iterator
  inc/classes/iterator/files/class-base.php
Labels: bug

#55 Switch to a recursive directory iterator for the file fetcher
  inc/classes/iterator/files/class-base.php
Labels: enhancement
